chat / notification 리팩토링
Nawabali-project/Nawabali-BE pull request #64
Opened 2024-04-09 11:46 UTC by minnieming

swagger 주석 추가

chat/notification 프론트와 맞추기 위해 주석 정리

2024-04-09 11:56 UTC, kyungmin1221 approved these changes
확인 했습니다!

2024-04-09 11:57 UTC, Peter-Yu-0402 approved these changes
고생하셨습니다! 감사합니다! :D

2024-04-10 02:19 UTC, juwum12 requested changes
user로 findall 해주세요

2024-04-10 02:19 UTC, juwum12 commented on src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
> +        userRepository.findById(user.getId())
유저정보를 받아오고 채팅방 목록반환에서 유저정보가 들어가있지 않은것 같은데 확인부탁드립니다.

2024-04-10 06:41 UTC, juwum12 approved these changes
고생하셨습니다.

2024-04-10 06:54 UTC, merged